In [1]:
from shapely.geometry import Point
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster
from folium.plugins import FastMarkerCluster

In [9]:
may = pd.read_csv('../data/may.csv/may.csv')

In [10]:
may.head()

pubdatetime   latitude  longitude        sumdid sumdtype  \
0  2019-05-01 00:01:41.247000  36.136822 -86.799877  PoweredLIRL1  Powered   
1  2019-05-01 00:01:41.247000  36.191252 -86.772945  PoweredXWRWC  Powered   
2  2019-05-01 00:01:41.247000  36.144752 -86.806293  PoweredMEJEH  Powered   
3  2019-05-01 00:01:41.247000  36.162056 -86.774688  Powered1A7TC  Powered   
4  2019-05-01 00:01:41.247000  36.150973 -86.783109  Powered2TYEF  Powered   

   chargelevel sumdgroup  costpermin companyname  
0         93.0   scooter         0.0        Bird  
1         35.0   scooter         0.0        Bird  
2         90.0   scooter         0.0        Bird  
3         88.0   scooter         0.0        Bird  
4         98.0   scooter         0.0        Bird

may.companyname.unique()

In [11]:
may.companyname.unique()

array(['Bird', 'Lyft', 'Gotcha', 'Lime', 'Spin', 'Jump', 'Bolt'],
      dtype=object)

In [12]:
may.sumdgroup.unique()

array(['scooter', 'Scooter', 'bicycle'], dtype=object)

In [14]:
may.sumdtype.unique()

array(['Powered', 'Standard'], dtype=object)

In [15]:
may['sumdtype'].value_counts()

Powered     20283582
Standard        8921
Name: sumdtype, dtype: int64

In [16]:
may['sumdgroup'].value_counts()

scooter    17542872
Scooter     2740710
bicycle        8921
Name: sumdgroup, dtype: int64

In [33]:
may.dtypes

pubdatetime     object
latitude       float64
longitude      float64
sumdid          object
sumdtype        object
chargelevel    float64
sumdgroup       object
costpermin     float64
companyname     object
dtype: object

In [34]:
may = may[may.sumdgroup != 'bicycle']

In [36]:
may['sumdgroup'].value_counts()

scooter    17542872
Scooter     2740710
Name: sumdgroup, dtype: int64

In [37]:
may['companyname'].value_counts()

Lime      7111655
Bird      4334006
Lyft      3112581
Jump      2984630
Spin      1301001
Gotcha     915314
Bolt       524395
Name: companyname, dtype: int64

In [38]:
may.dropna(inplace = True)

C:\Users\ferralme\Anaconda3\envs\geospatial\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [49]:
date = may["pubdatetime"].str.split(" ", n = 1, expand = True)

In [50]:
may['date'] = date[0]

C:\Users\ferralme\AppData\Local\Temp/ipykernel_14048/970717788.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may['date'] = date[0]


In [51]:
may['time'] = date[1]

C:\Users\ferralme\AppData\Local\Temp/ipykernel_14048/1448953827.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  may['time'] = date[1]


In [53]:
may.drop(columns=['pubdatetime'], inplace = True)

C:\Users\ferralme\Anaconda3\envs\geospatial\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [54]:
may.head()

latitude  longitude        sumdid sumdtype  chargelevel sumdgroup  \
0  36.136822 -86.799877  PoweredLIRL1  Powered         93.0   scooter   
1  36.191252 -86.772945  PoweredXWRWC  Powered         35.0   scooter   
2  36.144752 -86.806293  PoweredMEJEH  Powered         90.0   scooter   
3  36.162056 -86.774688  Powered1A7TC  Powered         88.0   scooter   
4  36.150973 -86.783109  Powered2TYEF  Powered         98.0   scooter   

   costpermin companyname        date             time  
0         0.0        Bird  2019-05-01  00:01:41.247000  
1         0.0        Bird  2019-05-01  00:01:41.247000  
2         0.0        Bird  2019-05-01  00:01:41.247000  
3         0.0        Bird  2019-05-01  00:01:41.247000  
4         0.0        Bird  2019-05-01  00:01:41.247000

In [56]:
may.shape

(20283299, 10)

In [57]:
scoot_names = may['sumdid'].value_counts()

PoweredIE7H5RIN474PE    8921
PoweredUK65LOU3K5N7G    8748
PoweredIOHG2G3XKATUL    8576
PoweredJCKMQCAL2SSNJ    8521
Powered4NYK5PWADVIAU    8439
                        ... 
PoweredGJYGPDVTFXRH7       1
PoweredYEBSU               1
PoweredCW742BQMJ3XHN       1
PoweredCI6VKIK2KOFMC       1
PoweredN4YI2A7RXZQLY       1
Name: sumdid, Length: 8301, dtype: int64

In [63]:
print(may['sumdid'].value_counts())

PoweredIE7H5RIN474PE    8921
PoweredUK65LOU3K5N7G    8748
PoweredIOHG2G3XKATUL    8576
PoweredJCKMQCAL2SSNJ    8521
Powered4NYK5PWADVIAU    8439
                        ... 
PoweredGJYGPDVTFXRH7       1
PoweredYEBSU               1
PoweredCW742BQMJ3XHN       1
PoweredCI6VKIK2KOFMC       1
PoweredN4YI2A7RXZQLY       1
Name: sumdid, Length: 8301, dtype: int64


in May there was 8,301 scooters that did 20,283,299 rides 

In [64]:
ridesperscooter = 20283299/8301
print(ridesperscooter)

2443.4765690880618
